### ISSUE TITLE
Add official support emails (ex. "carrot@rboxlo.xyz")

### ISSUE THREAD

**Issue by nxm3** [lighterlightbulb/Rboxlo#16]
add an email service to rboxlo instead of using gmail. kinda tedious

alternatively, get G Suite

**Comment by LordDamionDevil** [comment]
They can also just install an mail system/use the hosts mail or simply use Yandex Mail with their own domain.

**Comment by lighterlightbulb** [comment]
Originally we didn't want to do our own mail servers due to how complicated it is, and the fact that [DigitalOcean themselves not to set up your own mail server.](https://www.digitalocean.com/community/tutorials/why-you-may-not-want-to-run-your-own-mail-server) However, I have not heard of solutions like Yandex Mail; I will look into it. Thanks for the contribution.

**Comment by LordDamionDevil** [comment]
Here is an article which explains how to add a domain
https://yandex.com/support/connect/add-domain.html
after following the instructions you just follow this to create an mailbox
https://yandex.com/support/connect/create-mailbox.html

**Comment by lighterlightbulb** [comment]
Might I ask; where are you guys from? I haven't seen either of you in the old Roblox community at all, lol.

**Comment by LordDamionDevil** [comment]
I joined ROBLOX back in 2011 and also have a Finobe account + used to work for a site which tries to be BrickPlanet but says they arent

**Comment by nxm3** [comment]
I'm whatisthename

**Comment by lighterlightbulb** [comment]
This has been implemented.
